# Generated by Django 3.1 on 2021-05-22 23:23

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210518_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='imagen',
            field=models.ImageField(upload_to=backend.models.cambiar_ruta_de_fichero),
        ),
    ]
