# Generated by Django 3.1 on 2021-05-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210522_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='imagen',
            field=models.ImageField(upload_to='torneos'),
        ),
    ]
