# Generated by Django 3.1 on 2021-05-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210523_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='imagen',
            field=models.ImageField(upload_to='torneos'),
        ),
    ]
