# Generated by Django 3.1 on 2021-05-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210523_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='torneo',
            options={'ordering': ['nombre']},
        ),
    ]
