# Generated by Django 3.1 on 2021-05-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210523_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='escudo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='foto',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='correo_contacto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='telefono_contacto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
