# Generated by Django 3.1 on 2021-05-25 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0008_auto_20210523_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('inicia', models.DateTimeField()),
                ('termina', models.DateTimeField()),
                ('aviso', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.torneo')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipoA', models.IntegerField()),
                ('equipoB', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('hora', models.IntegerField()),
                ('minuto', models.IntegerField()),
                ('golesA', models.IntegerField()),
                ('golesB', models.IntegerField()),
                ('puntosA', models.IntegerField()),
                ('puntosB', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jornada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.jornada')),
                ('torneo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.torneo')),
            ],
            options={
                'ordering': ['fecha', 'hora', 'minuto'],
            },
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField()),
                ('tarjetas_amarillas', models.IntegerField()),
                ('tarjeta_roja', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.equipo')),
                ('juego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.juego')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.jugador')),
                ('torneo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.torneo')),
            ],
            options={
                'ordering': ['equipo'],
            },
        ),
    ]
