# Generated by Django 3.1 on 2021-06-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210606_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['clave']},
        ),
    ]
