# Generated by Django 3.1 on 2021-06-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210606_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='torneo_owner',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='torneo_owner',
            field=models.UUIDField(),
        ),
    ]
