# Generated by Django 3.1 on 2021-06-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210629_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='torneo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
