# Generated by Django 3.1 on 2021-08-30 21:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_visita_torneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='equipos')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoEscudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='escudos')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.equipo')),
            ],
        ),
    ]
